kind: APIConnectCluster
apiVersion: apiconnect.ibm.com/v1beta1
metadata:
  name: api-connect
  namespace: cp4i
  annotations:
    argocd.argoproj.io/sync-wave: "103"
spec:
  license:
    accept: true
    license: L-KZXM-S7SNCU
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: n1xc7.m48
  version: 10.0.6.0
  storageClassName: ocs-storagecluster-ceph-rbd