apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: api-connect
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
    license: L-KZXM-S7SNCU
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  profile: n1xc7.m48
  version: 10.0.6.0
  storageClassName: nfs