apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-license-service-reporter-operator-catalog
  namespace: openshift-marketplace
  labels:
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  displayName: IBM License Service Reporter Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-license-service-reporter-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m