apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: platform-navigator
  namespace: default
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
  replicas: 1
  version: 2023.4.1