apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: platform-navigator
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - 'resources-finalizer.argocd.argoproj.io'
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
  replicas: 1
  version: 2023.4.1