kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: ibm-common-services
  labels:
    kubernetes.io/metadata.name: ibm-common-services
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io