apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-licensing-operator-app.ibm-licensing: ''
  name: ibm-licensing-operator-app
  namespace: ibm-licensing
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: v4.2
  installPlanApproval: Automatic
  name: ibm-licensing-operator-app
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-licensing-operator.v4.2.1