apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-common-service-operator.openshift-operators: ''
  name: ibm-common-service-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: v4.3
  installPlanApproval: Automatic
  name: ibm-common-service-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-common-service-operator.v4.3.1