apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: platform-navigator
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  license:
    accept: true
    license: L-YBXJ-ADJNSM
  storage:
    class: nfs
  replicas: 1
  version: 2023.2.1