apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: licensing-og
  namespace: ibm-licensing
  labels:
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetNamespaces:
    - ibm-licensing