apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-common-service-operator.openshift-operators: ''
  name: ibm-common-service-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: v4.2
  installPlanApproval: Automatic
  name: ibm-common-service-operator
  source: opencloud-operators
  sourceNamespace: openshift-marketplace