apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    argocd.argoproj.io/managed-by: argocd
  name: ibm-common-service-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: v4.3
  installPlanApproval: Automatic
  name: ibm-common-service-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace